# Apprentissage Kubernetes - Marie F.
# Utilisation de labels sur les nodes - v1.0.0
#############################################
#
# Création d'un pod sur un node sélectionné
apiVersion: v1
kind: Pod
metadata:
  name: monpod
spec:
  containers:
    - image: alpine:latest
    name: monalpine
    command: ["/bin/sleep", "600"]
  nodeSelector:
    nodename: <nom d’un worker>

