apiVersion: v1
kind: Pod
metadata:
  name: monpod
spec:
  containers:
  - name: monnginx
    image: nginx:latest
  - name: monos
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - sleep 600
---
apiVersion: v1
kind: Pod
metadata:
  name: monpod2
  labels:
    app: frontend
    env: prod

spec:
  containers:
  - name: monnginx
    image: nginx:latest
  - name: monos
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - sleep 600

