# Apprentissage Kubernetes - Marie F.
# Utilisation de labels sur les pods - v1.0.0
#############################################
#
# Création d'un premier pod sans label
apiVersion: v1
kind: Pod
metadata:
  name: monpod
spec:
  containers:
  - name: monnginx
    image: nginx:latest
  - name: monos
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - sleep 600
---
# Création d'un second pod avec label
apiVersion: v1
kind: Pod
metadata:
  name: monpod2
  labels:
    app: frontend
    env: prod

spec:
  containers:
  - name: monnginx
    image: nginx:latest
  - name: monos
    image: ubuntu:latest
    args:
      - /bin/sh
      - -c
      - sleep 600

