apiVersion: v1
kind: Service
metadata:
  name: servicenginx
  namespace: ns-prod
spec:
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
