apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: utilisation-memoire
  namespace: ns-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utilisation-cpu
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        #type: Utilization
        #averageUtilization: 5
        type: AverageValue
        averageValue: 5m
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 25Mi
