# Création d'un namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prod
---
# Création d'un pod
apiVersion: v1
kind: Pod
metadata:
  name: monfrontend
  namespace: ns-prod
  labels:
    app: frontend
    env: dev
spec:
  containers:
  - name: monnginx
    image: nginx:latest

