# Apprentissage Kubernetes - Marie F.
# Création d'un pod- v1.0.0
#############################################
#
# Création d'un pod constitué de 2 containers 
apiVersion: v1
kind: Pod
metadata:
  name: monpod
spec:
  containers:
  - name: monnginx
    image: nginx:latest
  - name: monos
    image: alpine:latest
    args:
      - /bin/sh
      - -c
      - sleep 600

