apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfsrwx
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-manual
  nfs:
    path: <répertoire NFS exporté>
    server: <adresse du serveur NFS>
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pvc-nfs
  namespace: ns-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "nfs-manual"
